// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VM 运行状态
type VMStatus int32

const (
	VMStatus_VM_STATUS_UNSPECIFIED VMStatus = 0 // 未知
	VMStatus_VM_STATUS_CREATING    VMStatus = 1 // 创建中（等待 Agent 回报）
	VMStatus_VM_STATUS_RUNNING     VMStatus = 2 // 运行中
	VMStatus_VM_STATUS_STOPPED     VMStatus = 3 // 已停止
	VMStatus_VM_STATUS_EXPIRED     VMStatus = 4 // 已到期
	VMStatus_VM_STATUS_DELETED     VMStatus = 5 // 已删除
	VMStatus_VM_STATUS_ERROR       VMStatus = 6 // 异常
)

// Enum value maps for VMStatus.
var (
	VMStatus_name = map[int32]string{
		0: "VM_STATUS_UNSPECIFIED",
		1: "VM_STATUS_CREATING",
		2: "VM_STATUS_RUNNING",
		3: "VM_STATUS_STOPPED",
		4: "VM_STATUS_EXPIRED",
		5: "VM_STATUS_DELETED",
		6: "VM_STATUS_ERROR",
	}
	VMStatus_value = map[string]int32{
		"VM_STATUS_UNSPECIFIED": 0,
		"VM_STATUS_CREATING":    1,
		"VM_STATUS_RUNNING":     2,
		"VM_STATUS_STOPPED":     3,
		"VM_STATUS_EXPIRED":     4,
		"VM_STATUS_DELETED":     5,
		"VM_STATUS_ERROR":       6,
	}
)

func (x VMStatus) Enum() *VMStatus {
	p := new(VMStatus)
	*p = x
	return p
}

func (x VMStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (VMStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x VMStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMStatus.Descriptor instead.
func (VMStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

// 端口转发协议
type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[1].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[1]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

// Agent 发往平台的信封，每条消息携带唯一 message_id 用于追踪。
type AgentEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端生成的唯一消息 ID（用于去重 / 链路追踪）
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEnvelope_Heartbeat
	//	*AgentEnvelope_VmUpdate
	//	*AgentEnvelope_CmdResult
	//	*AgentEnvelope_PortFwdReport
	Payload       isAgentEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEnvelope) Reset() {
	*x = AgentEnvelope{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEnvelope) ProtoMessage() {}

func (x *AgentEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEnvelope.ProtoReflect.Descriptor instead.
func (*AgentEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentEnvelope) GetPayload() isAgentEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEnvelope) GetVmUpdate() *VMStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_VmUpdate); ok {
			return x.VmUpdate
		}
	}
	return nil
}

func (x *AgentEnvelope) GetCmdResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_CmdResult); ok {
			return x.CmdResult
		}
	}
	return nil
}

func (x *AgentEnvelope) GetPortFwdReport() *PortForwardReport {
	if x != nil {
		if x, ok := x.Payload.(*AgentEnvelope_PortFwdReport); ok {
			return x.PortFwdReport
		}
	}
	return nil
}

type isAgentEnvelope_Payload interface {
	isAgentEnvelope_Payload()
}

type AgentEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"` // 心跳（每 30 秒上报一次）
}

type AgentEnvelope_VmUpdate struct {
	VmUpdate *VMStatusUpdate `protobuf:"bytes,3,opt,name=vm_update,json=vmUpdate,proto3,oneof"` // VM 状态变化主动上报
}

type AgentEnvelope_CmdResult struct {
	CmdResult *CommandResult `protobuf:"bytes,4,opt,name=cmd_result,json=cmdResult,proto3,oneof"` // 平台命令的执行结果
}

type AgentEnvelope_PortFwdReport struct {
	PortFwdReport *PortForwardReport `protobuf:"bytes,5,opt,name=port_fwd_report,json=portFwdReport,proto3,oneof"` // 端口转发规则全量上报（启动 & 定期同步）
}

func (*AgentEnvelope_Heartbeat) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_VmUpdate) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_CmdResult) isAgentEnvelope_Payload() {}

func (*AgentEnvelope_PortFwdReport) isAgentEnvelope_Payload() {}

// 心跳包 — 携带宿主机实时负载与 VM 摘要列表。
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // Unix 秒
	CpuPct        float32                `protobuf:"fixed32,2,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`                      // CPU 使用率（0-100）
	RamUsedMb     int64                  `protobuf:"varint,3,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`            // 已用内存（MB）
	DiskUsedGb    int64                  `protobuf:"varint,4,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`         // 已用磁盘（GB）
	NetInBps      int64                  `protobuf:"varint,5,opt,name=net_in_bps,json=netInBps,proto3" json:"net_in_bps,omitempty"`               // 宿主机实时入口速率（bytes/s）
	NetOutBps     int64                  `protobuf:"varint,6,opt,name=net_out_bps,json=netOutBps,proto3" json:"net_out_bps,omitempty"`            // 宿主机实时出口速率（bytes/s）
	Load1         float32                `protobuf:"fixed32,11,opt,name=load1,proto3" json:"load1,omitempty"`                                     // 系统负载 (1 min)
	Load5         float32                `protobuf:"fixed32,12,opt,name=load5,proto3" json:"load5,omitempty"`                                     // 系统负载 (5 min)
	Load15        float32                `protobuf:"fixed32,13,opt,name=load15,proto3" json:"load15,omitempty"`                                   // 系统负载 (15 min)
	Uptime        int64                  `protobuf:"varint,14,opt,name=uptime,proto3" json:"uptime,omitempty"`                                    // 系统运行时间 (秒)
	Cpus          int32                  `protobuf:"varint,15,opt,name=cpus,proto3" json:"cpus,omitempty"`                                        // 逻辑 CPU 核数
	RamTotalMb    int64                  `protobuf:"varint,16,opt,name=ram_total_mb,json=ramTotalMb,proto3" json:"ram_total_mb,omitempty"`        // 总内存 (MB)
	DiskTotalGb   int64                  `protobuf:"varint,17,opt,name=disk_total_gb,json=diskTotalGb,proto3" json:"disk_total_gb,omitempty"`     // 总磁盘 (GB)
	BandwidthMbps int32                  `protobuf:"varint,18,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 总带宽 (Mbps)
	// 当前宿主机上所有 VM 的简要状态，用于平台侧对账。
	Vms []*VMSummary `protobuf:"bytes,7,rep,name=vms,proto3" json:"vms,omitempty"`
	// 宿主机入口地址（IPv4 / DDNS 域名），变化时才需要填写。
	EntryHost string `protobuf:"bytes,8,opt,name=entry_host,json=entryHost,proto3" json:"entry_host,omitempty"`
	// 宿主机 IPv6 地址（可选），变化时才需要填写。
	EntryIpv6 string `protobuf:"bytes,9,opt,name=entry_ipv6,json=entryIpv6,proto3" json:"entry_ipv6,omitempty"`
	// 宿主机支持的操作系统镜像列表。
	OsImages      []*OSImageInfo `protobuf:"bytes,10,rep,name=os_images,json=osImages,proto3" json:"os_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *Heartbeat) GetRamUsedMb() int64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *Heartbeat) GetDiskUsedGb() int64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *Heartbeat) GetNetInBps() int64 {
	if x != nil {
		return x.NetInBps
	}
	return 0
}

func (x *Heartbeat) GetNetOutBps() int64 {
	if x != nil {
		return x.NetOutBps
	}
	return 0
}

func (x *Heartbeat) GetLoad1() float32 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Heartbeat) GetLoad5() float32 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *Heartbeat) GetLoad15() float32 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *Heartbeat) GetUptime() int64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

func (x *Heartbeat) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *Heartbeat) GetRamTotalMb() int64 {
	if x != nil {
		return x.RamTotalMb
	}
	return 0
}

func (x *Heartbeat) GetDiskTotalGb() int64 {
	if x != nil {
		return x.DiskTotalGb
	}
	return 0
}

func (x *Heartbeat) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *Heartbeat) GetVms() []*VMSummary {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *Heartbeat) GetEntryHost() string {
	if x != nil {
		return x.EntryHost
	}
	return ""
}

func (x *Heartbeat) GetEntryIpv6() string {
	if x != nil {
		return x.EntryIpv6
	}
	return ""
}

func (x *Heartbeat) GetOsImages() []*OSImageInfo {
	if x != nil {
		return x.OsImages
	}
	return nil
}

// 操作系统镜像信息
type OSImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`     // 镜像唯一标识符
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 镜像显示名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSImageInfo) Reset() {
	*x = OSImageInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSImageInfo) ProtoMessage() {}

func (x *OSImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSImageInfo.ProtoReflect.Descriptor instead.
func (*OSImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *OSImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSImageInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// VM 状态摘要（心跳中内嵌）
type VMSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VmId              string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                                           // VM UUID
	Status            VMStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=agent.VMStatus" json:"status,omitempty"`                              // 当前状态
	CpuPct            float32                `protobuf:"fixed32,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`                                   // CPU 使用率（0-100）
	RamUsedMb         int64                  `protobuf:"varint,4,opt,name=ram_used_mb,json=ramUsedMb,proto3" json:"ram_used_mb,omitempty"`                         // 已用内存（MB）
	TrafficInBytes    int64                  `protobuf:"varint,5,opt,name=traffic_in_bytes,json=trafficInBytes,proto3" json:"traffic_in_bytes,omitempty"`          // 累计入站流量（bytes，自 VM 创建起）
	TrafficOutBytes   int64                  `protobuf:"varint,6,opt,name=traffic_out_bytes,json=trafficOutBytes,proto3" json:"traffic_out_bytes,omitempty"`       // 累计出站流量（bytes，自 VM 创建起）
	Ip                string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`                                                           // VM 内部/公网 IP
	MonthlyTrafficIn  int64                  `protobuf:"varint,8,opt,name=monthly_traffic_in,json=monthlyTrafficIn,proto3" json:"monthly_traffic_in,omitempty"`    // 本月累计入站流量 (bytes)
	MonthlyTrafficOut int64                  `protobuf:"varint,9,opt,name=monthly_traffic_out,json=monthlyTrafficOut,proto3" json:"monthly_traffic_out,omitempty"` // 本月累计出站流量 (bytes)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VMSummary) Reset() {
	*x = VMSummary{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSummary) ProtoMessage() {}

func (x *VMSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSummary.ProtoReflect.Descriptor instead.
func (*VMSummary) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *VMSummary) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMSummary) GetStatus() VMStatus {
	if x != nil {
		return x.Status
	}
	return VMStatus_VM_STATUS_UNSPECIFIED
}

func (x *VMSummary) GetCpuPct() float32 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *VMSummary) GetRamUsedMb() int64 {
	if x != nil {
		return x.RamUsedMb
	}
	return 0
}

func (x *VMSummary) GetTrafficInBytes() int64 {
	if x != nil {
		return x.TrafficInBytes
	}
	return 0
}

func (x *VMSummary) GetTrafficOutBytes() int64 {
	if x != nil {
		return x.TrafficOutBytes
	}
	return 0
}

func (x *VMSummary) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VMSummary) GetMonthlyTrafficIn() int64 {
	if x != nil {
		return x.MonthlyTrafficIn
	}
	return 0
}

func (x *VMSummary) GetMonthlyTrafficOut() int64 {
	if x != nil {
		return x.MonthlyTrafficOut
	}
	return 0
}

// 端口转发规则条目
type PortForwardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                  // VM UUID
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 宿主机端口
	GuestPort     int32                  `protobuf:"varint,4,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`  // VM 内部端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardEntry) Reset() {
	*x = PortForwardEntry{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardEntry) ProtoMessage() {}

func (x *PortForwardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardEntry.ProtoReflect.Descriptor instead.
func (*PortForwardEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PortForwardEntry) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *PortForwardEntry) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PortForwardEntry) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortForwardEntry) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

// Agent 主动上报当前实际生效的全量端口转发规则。
// 平台收到后与 DB 对比，推送差量命令（新增 / 删除）。
// 触发时机：Agent 启动时 & 定期（建议每 5 分钟）。
type PortForwardReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 宿主机上所有 VM 当前实际生效的端口转发规则
	Entries       []*PortForwardEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardReport) Reset() {
	*x = PortForwardReport{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardReport) ProtoMessage() {}

func (x *PortForwardReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardReport.ProtoReflect.Descriptor instead.
func (*PortForwardReport) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *PortForwardReport) GetEntries() []*PortForwardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// VM 状态变化主动上报（不等心跳，状态变更时立即发送）
type VMStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`              // VM UUID
	Status        VMStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=agent.VMStatus" json:"status,omitempty"` // 最新状态
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                    // 附加说明（如错误原因）
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                              // VM 内部/公网 IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMStatusUpdate) Reset() {
	*x = VMStatusUpdate{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMStatusUpdate) ProtoMessage() {}

func (x *VMStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMStatusUpdate.ProtoReflect.Descriptor instead.
func (*VMStatusUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *VMStatusUpdate) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMStatusUpdate) GetStatus() VMStatus {
	if x != nil {
		return x.Status
	}
	return VMStatus_VM_STATUS_UNSPECIFIED
}

func (x *VMStatusUpdate) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VMStatusUpdate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// 平台命令的执行结果
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 对应 PlatformEnvelope.command_id
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                     // 是否成功
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                          // 失败原因（success=false 时填写）
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                            // JSON 编码的附加结果数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 平台发往 Agent 的信封，每条命令携带唯一 command_id。
// Agent 执行完毕后须通过 CommandResult 回报结果。
type PlatformEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 平台生成的唯一命令 ID（持久化到 DB，用于重放）
	CommandId string `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PlatformEnvelope_CreateVm
	//	*PlatformEnvelope_StartVm
	//	*PlatformEnvelope_StopVm
	//	*PlatformEnvelope_RestartVm
	//	*PlatformEnvelope_DeleteVm
	//	*PlatformEnvelope_ResetPassword
	//	*PlatformEnvelope_SetPortFwd
	//	*PlatformEnvelope_DelPortFwd
	//	*PlatformEnvelope_GetVmInfo
	//	*PlatformEnvelope_SyncPortFwds
	//	*PlatformEnvelope_UpdateVm
	//	*PlatformEnvelope_ReinstallVm
	Payload       isPlatformEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformEnvelope) Reset() {
	*x = PlatformEnvelope{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformEnvelope) ProtoMessage() {}

func (x *PlatformEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformEnvelope.ProtoReflect.Descriptor instead.
func (*PlatformEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PlatformEnvelope) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PlatformEnvelope) GetPayload() isPlatformEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PlatformEnvelope) GetCreateVm() *CmdCreateVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_CreateVm); ok {
			return x.CreateVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetStartVm() *CmdStartVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_StartVm); ok {
			return x.StartVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetStopVm() *CmdStopVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_StopVm); ok {
			return x.StopVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetRestartVm() *CmdRestartVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_RestartVm); ok {
			return x.RestartVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetDeleteVm() *CmdDeleteVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_DeleteVm); ok {
			return x.DeleteVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetResetPassword() *CmdResetPassword {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ResetPassword); ok {
			return x.ResetPassword
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetSetPortFwd() *CmdSetPortForward {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_SetPortFwd); ok {
			return x.SetPortFwd
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetDelPortFwd() *CmdDelPortForward {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_DelPortFwd); ok {
			return x.DelPortFwd
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetGetVmInfo() *CmdGetVMInfo {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_GetVmInfo); ok {
			return x.GetVmInfo
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetSyncPortFwds() *CmdSyncPortForwards {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_SyncPortFwds); ok {
			return x.SyncPortFwds
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetUpdateVm() *CmdUpdateVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_UpdateVm); ok {
			return x.UpdateVm
		}
	}
	return nil
}

func (x *PlatformEnvelope) GetReinstallVm() *CmdReinstallVM {
	if x != nil {
		if x, ok := x.Payload.(*PlatformEnvelope_ReinstallVm); ok {
			return x.ReinstallVm
		}
	}
	return nil
}

type isPlatformEnvelope_Payload interface {
	isPlatformEnvelope_Payload()
}

type PlatformEnvelope_CreateVm struct {
	CreateVm *CmdCreateVM `protobuf:"bytes,2,opt,name=create_vm,json=createVm,proto3,oneof"` // 创建 VM
}

type PlatformEnvelope_StartVm struct {
	StartVm *CmdStartVM `protobuf:"bytes,3,opt,name=start_vm,json=startVm,proto3,oneof"` // 启动 VM
}

type PlatformEnvelope_StopVm struct {
	StopVm *CmdStopVM `protobuf:"bytes,4,opt,name=stop_vm,json=stopVm,proto3,oneof"` // 关闭 VM
}

type PlatformEnvelope_RestartVm struct {
	RestartVm *CmdRestartVM `protobuf:"bytes,5,opt,name=restart_vm,json=restartVm,proto3,oneof"` // 重启 VM
}

type PlatformEnvelope_DeleteVm struct {
	DeleteVm *CmdDeleteVM `protobuf:"bytes,6,opt,name=delete_vm,json=deleteVm,proto3,oneof"` // 销毁 VM
}

type PlatformEnvelope_ResetPassword struct {
	ResetPassword *CmdResetPassword `protobuf:"bytes,7,opt,name=reset_password,json=resetPassword,proto3,oneof"` // 重置 root 密码
}

type PlatformEnvelope_SetPortFwd struct {
	SetPortFwd *CmdSetPortForward `protobuf:"bytes,8,opt,name=set_port_fwd,json=setPortFwd,proto3,oneof"` // 新增单条端口转发规则
}

type PlatformEnvelope_DelPortFwd struct {
	DelPortFwd *CmdDelPortForward `protobuf:"bytes,9,opt,name=del_port_fwd,json=delPortFwd,proto3,oneof"` // 删除单条端口转发规则
}

type PlatformEnvelope_GetVmInfo struct {
	GetVmInfo *CmdGetVMInfo `protobuf:"bytes,10,opt,name=get_vm_info,json=getVmInfo,proto3,oneof"` // 查询 VM 详情
}

type PlatformEnvelope_SyncPortFwds struct {
	SyncPortFwds *CmdSyncPortForwards `protobuf:"bytes,11,opt,name=sync_port_fwds,json=syncPortFwds,proto3,oneof"` // 全量同步某 VM 的端口转发规则（Agent 以此为准）
}

type PlatformEnvelope_UpdateVm struct {
	UpdateVm *CmdUpdateVM `protobuf:"bytes,12,opt,name=update_vm,json=updateVm,proto3,oneof"` // 修改 VM 配置 (机主/管理员)
}

type PlatformEnvelope_ReinstallVm struct {
	ReinstallVm *CmdReinstallVM `protobuf:"bytes,13,opt,name=reinstall_vm,json=reinstallVm,proto3,oneof"` // 重装 VM 系统
}

func (*PlatformEnvelope_CreateVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_StartVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_StopVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_RestartVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_DeleteVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ResetPassword) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_SetPortFwd) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_DelPortFwd) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_GetVmInfo) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_SyncPortFwds) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_UpdateVm) isPlatformEnvelope_Payload() {}

func (*PlatformEnvelope_ReinstallVm) isPlatformEnvelope_Payload() {}

// 重装 VM
type CmdReinstallVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                         // VM UUID
	OsImage       string                 `protobuf:"bytes,2,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`                // 新操作系统镜像 ID
	RootPassword  string                 `protobuf:"bytes,3,opt,name=root_password,json=rootPassword,proto3" json:"root_password,omitempty"` // 新 root 密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdReinstallVM) Reset() {
	*x = CmdReinstallVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdReinstallVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdReinstallVM) ProtoMessage() {}

func (x *CmdReinstallVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdReinstallVM.ProtoReflect.Descriptor instead.
func (*CmdReinstallVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CmdReinstallVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdReinstallVM) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *CmdReinstallVM) GetRootPassword() string {
	if x != nil {
		return x.RootPassword
	}
	return ""
}

// 修改 VM 配置
type CmdUpdateVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                             // VM UUID
	Cpu           int32                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`                                          // 新 CPU 核数 (0 表示不修改)
	RamMb         int64                  `protobuf:"varint,3,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`                         // 新内存 MB (0 表示不修改)
	DiskGb        int64                  `protobuf:"varint,4,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`                      // 新磁盘 GB (0 表示不修改)
	BandwidthMbps int32                  `protobuf:"varint,5,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 新带宽 Mbps (负数表示不修改)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdUpdateVM) Reset() {
	*x = CmdUpdateVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdUpdateVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdUpdateVM) ProtoMessage() {}

func (x *CmdUpdateVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdUpdateVM.ProtoReflect.Descriptor instead.
func (*CmdUpdateVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CmdUpdateVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdUpdateVM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CmdUpdateVM) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *CmdUpdateVM) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CmdUpdateVM) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

// 创建 VM
type CmdCreateVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                             // VM UUID（Agent 侧用作标识符）
	Cpu           int32                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`                                          // CPU 核数
	RamMb         int64                  `protobuf:"varint,3,opt,name=ram_mb,json=ramMb,proto3" json:"ram_mb,omitempty"`                         // 内存（MB）
	DiskGb        int64                  `protobuf:"varint,4,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`                      // 磁盘（GB）
	BandwidthMbps int32                  `protobuf:"varint,5,opt,name=bandwidth_mbps,json=bandwidthMbps,proto3" json:"bandwidth_mbps,omitempty"` // 带宽限速（Mbps），0 = 不限
	OsImage       string                 `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`                    // 操作系统镜像 ID / 名称
	RootPassword  string                 `protobuf:"bytes,7,opt,name=root_password,json=rootPassword,proto3" json:"root_password,omitempty"`     // root 初始密码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdCreateVM) Reset() {
	*x = CmdCreateVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdCreateVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdCreateVM) ProtoMessage() {}

func (x *CmdCreateVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdCreateVM.ProtoReflect.Descriptor instead.
func (*CmdCreateVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *CmdCreateVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdCreateVM) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CmdCreateVM) GetRamMb() int64 {
	if x != nil {
		return x.RamMb
	}
	return 0
}

func (x *CmdCreateVM) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CmdCreateVM) GetBandwidthMbps() int32 {
	if x != nil {
		return x.BandwidthMbps
	}
	return 0
}

func (x *CmdCreateVM) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *CmdCreateVM) GetRootPassword() string {
	if x != nil {
		return x.RootPassword
	}
	return ""
}

// 启动 VM
type CmdStartVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStartVM) Reset() {
	*x = CmdStartVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStartVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStartVM) ProtoMessage() {}

func (x *CmdStartVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStartVM.ProtoReflect.Descriptor instead.
func (*CmdStartVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CmdStartVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// 关闭 VM
type CmdStopVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`          // true = 强制关机（等同于断电）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdStopVM) Reset() {
	*x = CmdStopVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdStopVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdStopVM) ProtoMessage() {}

func (x *CmdStopVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdStopVM.ProtoReflect.Descriptor instead.
func (*CmdStopVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CmdStopVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdStopVM) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

// 重启 VM
type CmdRestartVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRestartVM) Reset() {
	*x = CmdRestartVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRestartVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRestartVM) ProtoMessage() {}

func (x *CmdRestartVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRestartVM.ProtoReflect.Descriptor instead.
func (*CmdRestartVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CmdRestartVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// 销毁 VM（不可恢复，释放所有资源）
type CmdDeleteVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDeleteVM) Reset() {
	*x = CmdDeleteVM{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDeleteVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDeleteVM) ProtoMessage() {}

func (x *CmdDeleteVM) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDeleteVM.ProtoReflect.Descriptor instead.
func (*CmdDeleteVM) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *CmdDeleteVM) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// 重置 root 密码
type CmdResetPassword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                      // VM UUID
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"` // 新密码（明文，Agent 负责写入）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdResetPassword) Reset() {
	*x = CmdResetPassword{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdResetPassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdResetPassword) ProtoMessage() {}

func (x *CmdResetPassword) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdResetPassword.ProtoReflect.Descriptor instead.
func (*CmdResetPassword) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *CmdResetPassword) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdResetPassword) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// 新增端口转发规则（宿主机端口 → VM 内部端口）
type CmdSetPortForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                  // VM UUID
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 宿主机端口（1024-65535）
	GuestPort     int32                  `protobuf:"varint,4,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`  // VM 内部端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdSetPortForward) Reset() {
	*x = CmdSetPortForward{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdSetPortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdSetPortForward) ProtoMessage() {}

func (x *CmdSetPortForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdSetPortForward.ProtoReflect.Descriptor instead.
func (*CmdSetPortForward) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CmdSetPortForward) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdSetPortForward) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CmdSetPortForward) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *CmdSetPortForward) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

// 删除端口转发规则
type CmdDelPortForward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`                  // VM UUID
	Protocol      Protocol               `protobuf:"varint,2,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议
	HostPort      int32                  `protobuf:"varint,3,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 要删除的宿主机端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdDelPortForward) Reset() {
	*x = CmdDelPortForward{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdDelPortForward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdDelPortForward) ProtoMessage() {}

func (x *CmdDelPortForward) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdDelPortForward.ProtoReflect.Descriptor instead.
func (*CmdDelPortForward) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CmdDelPortForward) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdDelPortForward) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *CmdDelPortForward) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

// 查询 VM 详情（返回结果通过 CommandResult.data 以 JSON 编码回传）
type CmdGetVMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdGetVMInfo) Reset() {
	*x = CmdGetVMInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdGetVMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdGetVMInfo) ProtoMessage() {}

func (x *CmdGetVMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdGetVMInfo.ProtoReflect.Descriptor instead.
func (*CmdGetVMInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *CmdGetVMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

// 全量同步某 VM 的端口转发规则。
// Agent 收到后以此列表为权威，补充缺失、清除多余。
type CmdSyncPortForwards struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	VmId  string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // VM UUID
	// 该 VM 期望生效的完整端口转发规则列表（空列表 = 清除全部）
	Rules         []*PortForwardRule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdSyncPortForwards) Reset() {
	*x = CmdSyncPortForwards{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdSyncPortForwards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdSyncPortForwards) ProtoMessage() {}

func (x *CmdSyncPortForwards) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdSyncPortForwards.ProtoReflect.Descriptor instead.
func (*CmdSyncPortForwards) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *CmdSyncPortForwards) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CmdSyncPortForwards) GetRules() []*PortForwardRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 单条端口转发规则（用于 CmdSyncPortForwards）
type PortForwardRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      Protocol               `protobuf:"varint,1,opt,name=protocol,proto3,enum=agent.Protocol" json:"protocol,omitempty"` // 协议
	HostPort      int32                  `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`     // 宿主机端口（1024-65535）
	GuestPort     int32                  `protobuf:"varint,3,opt,name=guest_port,json=guestPort,proto3" json:"guest_port,omitempty"`  // VM 内部端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortForwardRule) Reset() {
	*x = PortForwardRule{}
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortForwardRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortForwardRule) ProtoMessage() {}

func (x *PortForwardRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortForwardRule.ProtoReflect.Descriptor instead.
func (*PortForwardRule) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PortForwardRule) GetProtocol() Protocol {
	if x != nil {
		return x.Protocol
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *PortForwardRule) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortForwardRule) GetGuestPort() int32 {
	if x != nil {
		return x.GuestPort
	}
	return 0
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\x9c\x02\n" +
	"\rAgentEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x120\n" +
	"\theartbeat\x18\x02 \x01(\v2\x10.agent.HeartbeatH\x00R\theartbeat\x124\n" +
	"\tvm_update\x18\x03 \x01(\v2\x15.agent.VMStatusUpdateH\x00R\bvmUpdate\x125\n" +
	"\n" +
	"cmd_result\x18\x04 \x01(\v2\x14.agent.CommandResultH\x00R\tcmdResult\x12B\n" +
	"\x0fport_fwd_report\x18\x05 \x01(\v2\x18.agent.PortForwardReportH\x00R\rportFwdReportB\t\n" +
	"\apayload\"\xb2\x04\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\acpu_pct\x18\x02 \x01(\x02R\x06cpuPct\x12\x1e\n" +
	"\vram_used_mb\x18\x03 \x01(\x03R\tramUsedMb\x12 \n" +
	"\fdisk_used_gb\x18\x04 \x01(\x03R\n" +
	"diskUsedGb\x12\x1c\n" +
	"\n" +
	"net_in_bps\x18\x05 \x01(\x03R\bnetInBps\x12\x1e\n" +
	"\vnet_out_bps\x18\x06 \x01(\x03R\tnetOutBps\x12\x14\n" +
	"\x05load1\x18\v \x01(\x02R\x05load1\x12\x14\n" +
	"\x05load5\x18\f \x01(\x02R\x05load5\x12\x16\n" +
	"\x06load15\x18\r \x01(\x02R\x06load15\x12\x16\n" +
	"\x06uptime\x18\x0e \x01(\x03R\x06uptime\x12\x12\n" +
	"\x04cpus\x18\x0f \x01(\x05R\x04cpus\x12 \n" +
	"\fram_total_mb\x18\x10 \x01(\x03R\n" +
	"ramTotalMb\x12\"\n" +
	"\rdisk_total_gb\x18\x11 \x01(\x03R\vdiskTotalGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x12 \x01(\x05R\rbandwidthMbps\x12\"\n" +
	"\x03vms\x18\a \x03(\v2\x10.agent.VMSummaryR\x03vms\x12\x1d\n" +
	"\n" +
	"entry_host\x18\b \x01(\tR\tentryHost\x12\x1d\n" +
	"\n" +
	"entry_ipv6\x18\t \x01(\tR\tentryIpv6\x12/\n" +
	"\tos_images\x18\n" +
	" \x03(\v2\x12.agent.OSImageInfoR\bosImages\"1\n" +
	"\vOSImageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc6\x02\n" +
	"\tVMSummary\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.agent.VMStatusR\x06status\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x02R\x06cpuPct\x12\x1e\n" +
	"\vram_used_mb\x18\x04 \x01(\x03R\tramUsedMb\x12(\n" +
	"\x10traffic_in_bytes\x18\x05 \x01(\x03R\x0etrafficInBytes\x12*\n" +
	"\x11traffic_out_bytes\x18\x06 \x01(\x03R\x0ftrafficOutBytes\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12,\n" +
	"\x12monthly_traffic_in\x18\b \x01(\x03R\x10monthlyTrafficIn\x12.\n" +
	"\x13monthly_traffic_out\x18\t \x01(\x03R\x11monthlyTrafficOut\"\x90\x01\n" +
	"\x10PortForwardEntry\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x04 \x01(\x05R\tguestPort\"F\n" +
	"\x11PortForwardReport\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.agent.PortForwardEntryR\aentries\"x\n" +
	"\x0eVMStatusUpdate\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.agent.VMStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\"r\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"\xdd\x05\n" +
	"\x10PlatformEnvelope\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\tcreate_vm\x18\x02 \x01(\v2\x12.agent.CmdCreateVMH\x00R\bcreateVm\x12.\n" +
	"\bstart_vm\x18\x03 \x01(\v2\x11.agent.CmdStartVMH\x00R\astartVm\x12+\n" +
	"\astop_vm\x18\x04 \x01(\v2\x10.agent.CmdStopVMH\x00R\x06stopVm\x124\n" +
	"\n" +
	"restart_vm\x18\x05 \x01(\v2\x13.agent.CmdRestartVMH\x00R\trestartVm\x121\n" +
	"\tdelete_vm\x18\x06 \x01(\v2\x12.agent.CmdDeleteVMH\x00R\bdeleteVm\x12@\n" +
	"\x0ereset_password\x18\a \x01(\v2\x17.agent.CmdResetPasswordH\x00R\rresetPassword\x12<\n" +
	"\fset_port_fwd\x18\b \x01(\v2\x18.agent.CmdSetPortForwardH\x00R\n" +
	"setPortFwd\x12<\n" +
	"\fdel_port_fwd\x18\t \x01(\v2\x18.agent.CmdDelPortForwardH\x00R\n" +
	"delPortFwd\x125\n" +
	"\vget_vm_info\x18\n" +
	" \x01(\v2\x13.agent.CmdGetVMInfoH\x00R\tgetVmInfo\x12B\n" +
	"\x0esync_port_fwds\x18\v \x01(\v2\x1a.agent.CmdSyncPortForwardsH\x00R\fsyncPortFwds\x121\n" +
	"\tupdate_vm\x18\f \x01(\v2\x12.agent.CmdUpdateVMH\x00R\bupdateVm\x12:\n" +
	"\freinstall_vm\x18\r \x01(\v2\x15.agent.CmdReinstallVMH\x00R\vreinstallVmB\t\n" +
	"\apayload\"e\n" +
	"\x0eCmdReinstallVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x19\n" +
	"\bos_image\x18\x02 \x01(\tR\aosImage\x12#\n" +
	"\rroot_password\x18\x03 \x01(\tR\frootPassword\"\x8b\x01\n" +
	"\vCmdUpdateVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x05R\x03cpu\x12\x15\n" +
	"\x06ram_mb\x18\x03 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x04 \x01(\x03R\x06diskGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x05 \x01(\x05R\rbandwidthMbps\"\xcb\x01\n" +
	"\vCmdCreateVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x05R\x03cpu\x12\x15\n" +
	"\x06ram_mb\x18\x03 \x01(\x03R\x05ramMb\x12\x17\n" +
	"\adisk_gb\x18\x04 \x01(\x03R\x06diskGb\x12%\n" +
	"\x0ebandwidth_mbps\x18\x05 \x01(\x05R\rbandwidthMbps\x12\x19\n" +
	"\bos_image\x18\x06 \x01(\tR\aosImage\x12#\n" +
	"\rroot_password\x18\a \x01(\tR\frootPassword\"!\n" +
	"\n" +
	"CmdStartVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"6\n" +
	"\tCmdStopVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"#\n" +
	"\fCmdRestartVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\"\n" +
	"\vCmdDeleteVM\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"J\n" +
	"\x10CmdResetPassword\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x91\x01\n" +
	"\x11CmdSetPortForward\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x04 \x01(\x05R\tguestPort\"r\n" +
	"\x11CmdDelPortForward\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12+\n" +
	"\bprotocol\x18\x02 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x03 \x01(\x05R\bhostPort\"#\n" +
	"\fCmdGetVMInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"X\n" +
	"\x13CmdSyncPortForwards\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12,\n" +
	"\x05rules\x18\x02 \x03(\v2\x16.agent.PortForwardRuleR\x05rules\"z\n" +
	"\x0fPortForwardRule\x12+\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x0f.agent.ProtocolR\bprotocol\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\x05R\bhostPort\x12\x1d\n" +
	"\n" +
	"guest_port\x18\x03 \x01(\x05R\tguestPort*\xae\x01\n" +
	"\bVMStatus\x12\x19\n" +
	"\x15VM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12VM_STATUS_CREATING\x10\x01\x12\x15\n" +
	"\x11VM_STATUS_RUNNING\x10\x02\x12\x15\n" +
	"\x11VM_STATUS_STOPPED\x10\x03\x12\x15\n" +
	"\x11VM_STATUS_EXPIRED\x10\x04\x12\x15\n" +
	"\x11VM_STATUS_DELETED\x10\x05\x12\x13\n" +
	"\x0fVM_STATUS_ERROR\x10\x06*H\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x022L\n" +
	"\fAgentGateway\x12<\n" +
	"\aConnect\x12\x14.agent.AgentEnvelope\x1a\x17.agent.PlatformEnvelope(\x010\x01B\x17Z\x15runman-v2/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_agent_agent_proto_goTypes = []any{
	(VMStatus)(0),               // 0: agent.VMStatus
	(Protocol)(0),               // 1: agent.Protocol
	(*AgentEnvelope)(nil),       // 2: agent.AgentEnvelope
	(*Heartbeat)(nil),           // 3: agent.Heartbeat
	(*OSImageInfo)(nil),         // 4: agent.OSImageInfo
	(*VMSummary)(nil),           // 5: agent.VMSummary
	(*PortForwardEntry)(nil),    // 6: agent.PortForwardEntry
	(*PortForwardReport)(nil),   // 7: agent.PortForwardReport
	(*VMStatusUpdate)(nil),      // 8: agent.VMStatusUpdate
	(*CommandResult)(nil),       // 9: agent.CommandResult
	(*PlatformEnvelope)(nil),    // 10: agent.PlatformEnvelope
	(*CmdReinstallVM)(nil),      // 11: agent.CmdReinstallVM
	(*CmdUpdateVM)(nil),         // 12: agent.CmdUpdateVM
	(*CmdCreateVM)(nil),         // 13: agent.CmdCreateVM
	(*CmdStartVM)(nil),          // 14: agent.CmdStartVM
	(*CmdStopVM)(nil),           // 15: agent.CmdStopVM
	(*CmdRestartVM)(nil),        // 16: agent.CmdRestartVM
	(*CmdDeleteVM)(nil),         // 17: agent.CmdDeleteVM
	(*CmdResetPassword)(nil),    // 18: agent.CmdResetPassword
	(*CmdSetPortForward)(nil),   // 19: agent.CmdSetPortForward
	(*CmdDelPortForward)(nil),   // 20: agent.CmdDelPortForward
	(*CmdGetVMInfo)(nil),        // 21: agent.CmdGetVMInfo
	(*CmdSyncPortForwards)(nil), // 22: agent.CmdSyncPortForwards
	(*PortForwardRule)(nil),     // 23: agent.PortForwardRule
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	3,  // 0: agent.AgentEnvelope.heartbeat:type_name -> agent.Heartbeat
	8,  // 1: agent.AgentEnvelope.vm_update:type_name -> agent.VMStatusUpdate
	9,  // 2: agent.AgentEnvelope.cmd_result:type_name -> agent.CommandResult
	7,  // 3: agent.AgentEnvelope.port_fwd_report:type_name -> agent.PortForwardReport
	5,  // 4: agent.Heartbeat.vms:type_name -> agent.VMSummary
	4,  // 5: agent.Heartbeat.os_images:type_name -> agent.OSImageInfo
	0,  // 6: agent.VMSummary.status:type_name -> agent.VMStatus
	1,  // 7: agent.PortForwardEntry.protocol:type_name -> agent.Protocol
	6,  // 8: agent.PortForwardReport.entries:type_name -> agent.PortForwardEntry
	0,  // 9: agent.VMStatusUpdate.status:type_name -> agent.VMStatus
	13, // 10: agent.PlatformEnvelope.create_vm:type_name -> agent.CmdCreateVM
	14, // 11: agent.PlatformEnvelope.start_vm:type_name -> agent.CmdStartVM
	15, // 12: agent.PlatformEnvelope.stop_vm:type_name -> agent.CmdStopVM
	16, // 13: agent.PlatformEnvelope.restart_vm:type_name -> agent.CmdRestartVM
	17, // 14: agent.PlatformEnvelope.delete_vm:type_name -> agent.CmdDeleteVM
	18, // 15: agent.PlatformEnvelope.reset_password:type_name -> agent.CmdResetPassword
	19, // 16: agent.PlatformEnvelope.set_port_fwd:type_name -> agent.CmdSetPortForward
	20, // 17: agent.PlatformEnvelope.del_port_fwd:type_name -> agent.CmdDelPortForward
	21, // 18: agent.PlatformEnvelope.get_vm_info:type_name -> agent.CmdGetVMInfo
	22, // 19: agent.PlatformEnvelope.sync_port_fwds:type_name -> agent.CmdSyncPortForwards
	12, // 20: agent.PlatformEnvelope.update_vm:type_name -> agent.CmdUpdateVM
	11, // 21: agent.PlatformEnvelope.reinstall_vm:type_name -> agent.CmdReinstallVM
	1,  // 22: agent.CmdSetPortForward.protocol:type_name -> agent.Protocol
	1,  // 23: agent.CmdDelPortForward.protocol:type_name -> agent.Protocol
	23, // 24: agent.CmdSyncPortForwards.rules:type_name -> agent.PortForwardRule
	1,  // 25: agent.PortForwardRule.protocol:type_name -> agent.Protocol
	2,  // 26: agent.AgentGateway.Connect:input_type -> agent.AgentEnvelope
	10, // 27: agent.AgentGateway.Connect:output_type -> agent.PlatformEnvelope
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	file_proto_agent_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentEnvelope_Heartbeat)(nil),
		(*AgentEnvelope_VmUpdate)(nil),
		(*AgentEnvelope_CmdResult)(nil),
		(*AgentEnvelope_PortFwdReport)(nil),
	}
	file_proto_agent_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*PlatformEnvelope_CreateVm)(nil),
		(*PlatformEnvelope_StartVm)(nil),
		(*PlatformEnvelope_StopVm)(nil),
		(*PlatformEnvelope_RestartVm)(nil),
		(*PlatformEnvelope_DeleteVm)(nil),
		(*PlatformEnvelope_ResetPassword)(nil),
		(*PlatformEnvelope_SetPortFwd)(nil),
		(*PlatformEnvelope_DelPortFwd)(nil),
		(*PlatformEnvelope_GetVmInfo)(nil),
		(*PlatformEnvelope_SyncPortFwds)(nil),
		(*PlatformEnvelope_UpdateVm)(nil),
		(*PlatformEnvelope_ReinstallVm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
